### ISSUE TITLE
Limine fails when Font and Wallpaper are provided

### ISSUE THREAD

**Issue by h4ckee** [Limine-Bootloader/Limine#176] opened 2022-05-28 10:29 UTC
Limine fails to boot when `TERM_WALLPAPER` and `TERM_FONT` are provided -
[https://drive.google.com/file/d/1CkCVJkV9cBkNwCFYW_XxvriSM0P2CIuC/view?usp=sharing](https://drive.google.com/file/d/1CkCVJkV9cBkNwCFYW_XxvriSM0P2CIuC/view?usp=sharing)
If commented out limine boots fine - 
[https://drive.google.com/file/d/1HtTqo0_20NLAh0nf_sEOC7mggFd9I2ey/view?usp=sharing](https://drive.google.com/file/d/1HtTqo0_20NLAh0nf_sEOC7mggFd9I2ey/view?usp=sharing)

Here is the limine.cfg:
> ${KERNEL}=boot:///boot/vmlinuz
> ${ARGS}=root=/dev/sda1 ro vt.default_red=21,202,171,196,135,204,65,231,104,227,175,224,115,225,108,240 vt.default_grn=21,94,203,141,135,152,129,231,104,54,215,167,115,162,191,240 vt.default_blu=21,94,141,98,175,224,121,231,104,54,138,101,201,220,196,240
> 
> TERM_WALLPAPER=boot:///boot/splash.bmp
> TERM_FONT=boot:///boot/tosh-sat.f16
> TERM_FONT_SIZE=9x16
> INTERFACE_RESOLUTION=1600x900
> INTERFACE_BRANDING=***** AXE *****
> INTERFACE_BRANDING_COLOR=1
> DEFAULT_ENTRY=1
> GRAPHICS=yes
> TIMEOUT=3
> TERM_BACKDROP=262626
> TERM_FOREGROUND=A8A8A8
> TERM_BACKGROUND=51262626
> TERM_PALETTE=151515;CA5E5E;ABCB8D;C48D62;8787AF;CC98E0;418179;E7E7E7
> TERM_PALETTE_BRIGHT=686868;E33636;AFD78A;E0A765;7373C9;E1A2DC;6CBFC4;F0F0F0
> 
> :Boot
>         PROTOCOL=linux
>         KERNEL_PATH=${KERNEL}
>         KERNEL_CMDLINE=${ARGS} mds=full quiet
> 
> :Safe Mode
>         PROTOCOL=linux
>         KERNEL_PATH=${KERNEL}
>         KERNEL_CMDLINE=${ARGS} single

> $ doas fdisk -l
> Disk /dev/sda: 4 GiB, 4294967296 bytes, 8388608 sectors
> Disk model: VBOX HARDDISK
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: gpt
> Disk identifier: C6ABA0D7-B303-794C-9064-E042D2983AD1
> 
> Device       Start     End Sectors  Size Type
> /dev/sda1     2048 7170047 7168000  3,4G Linux filesystem
> /dev/sda2  7170048 8386559 1216512  594M Linux swap
> $ uname -a
> Linux AXE 5.10.117 #2 SMP PREEMPT Wed, 25 May 2022 13:41:28 +0000 x86_64 GNU/Linux
> $ free -h
>                total        used        free      shared  buff/cache   available
> Mem:           993Mi        13Mi       949Mi       0,0Ki        29Mi       887Mi
> Swap:          593Mi          0B       593Mi

Link to the font:
[https://github.com/viler-int10h/vga-text-mode-fonts/blob/master/FONTS/PC-OTHER/TOSH-SAT.F16](https://github.com/viler-int10h/vga-text-mode-fonts/blob/master/FONTS/PC-OTHER/TOSH-SAT.F16)

Link to the wallpaper:
[https://drive.google.com/file/d/1WWNO1zgH9OF1OYf4iyfIAejMifU7foOy/view?usp=sharing](https://drive.google.com/file/d/1WWNO1zgH9OF1OYf4iyfIAejMifU7foOy/view?usp=sharing)

**Comment by Mintsuki** [comment] 2022-05-29 01:55
Hi,

I cannot reproduce the issue. Using the provided font and background works fine for me.

Are you sure something else isn't the cause? Also, what Limine version is this?

**Comment by h4ckee** [comment] 2022-05-29 13:46
Limine version is 3.5
Looks like I've found the problem. It was related to `TERM_FONT` and `TERM_FONT_SIZE` settings. When I changed it from **9x16** to **8x16**, everything began to work as expected.
Though similar configuration doesn't work on my Thinkpad T430.
I have a separate /boot partition there with ext2 and following config:

> ${KERNEL}=boot:///vmlinuz
> ${ARGS}=root=/dev/sdb2 ro vt.default_red=21,202,171,196,135,204,65,231,104,227,175,224,115,225,108,240 vt.default_grn=21,94,203,141,135,152,129,231,104,54,215,167,115,162,191,240 vt.default_blu=21,94,141,98,175,224,121,231,104,54,138,101,201,220,196,240
> 
> TERM_WALLPAPER=boot:///splash.bmp
> TERM_FONT=boot:///tosh-sat.f16
> TERM_FONT_SIZE=8x16
> INTERFACE_RESOLUTION=1600x900
> INTERFACE_BRANDING=***** AXE *****
> INTERFACE_BRANDING_COLOR=1
> DEFAULT_ENTRY=1
> GRAPHICS=yes
> TIMEOUT=3
> TERM_BACKDROP=262626
> TERM_FOREGROUND=A8A8A8
> TERM_BACKGROUND=51262626
> TERM_PALETTE=151515;CA5E5E;ABCB8D;C48D62;8787AF;CC98E0;418179;E7E7E7
> TERM_PALETTE_BRIGHT=686868;E33636;AFD78A;E0A765;7373C9;E1A2DC;6CBFC4;F0F0F0
> 
> :Boot
>         PROTOCOL=linux
>         KERNEL_PATH=${KERNEL}
>         KERNEL_CMDLINE=${ARGS} mds=full pcie_aspm=off quiet
> 
> :Safe Mode
>         PROTOCOL=linux
>         KERNEL_PATH=${KERNEL}
>         KERNEL_CMDLINE=${ARGS} single

When I boot the laptop everything I see is a black screen with shimmering underscore. Extlinux works fine.

> $ doas fdisk -l
> Disk /dev/sda: 465,76 GiB, 500107862016 bytes, 976773168 sectors
> Disk model: ST500LM021-1KJ15
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 4096 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> Disklabel type: gpt
> Disk identifier: 933508FA-06C1-D545-8CCA-ED287EC68F09
> 
> Device         Start       End   Sectors  Size Type
> /dev/sda1       2048 964691967 964689920  460G Linux filesystem
> /dev/sda2  973080576 976773134   3692559  1,8G Linux swap
> /dev/sda3  964691968 973080575   8388608    4G Linux filesystem
> 
> Partition table entries are not in disk order.
> 
> 
> Disk /dev/sdb: 59,63 GiB, 64023257088 bytes, 125045424 sectors
> Disk model: PLEXTOR PX-64M5M
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: gpt
> Disk identifier: 9C09ADB7-65CC-9444-89A5-9242B75364A2
> 
> Device      Start       End   Sectors  Size Type
> /dev/sdb1    2048    133119    131072   64M Linux filesystem
> /dev/sdb2  133120 125045390 124912271 59,6G Linux filesystem

**Comment by Mintsuki** [comment] 2022-06-19 18:25
Closing this as unable to reproduce

**Closed as completed** 2022-06-19 18:25 UTC
