### ISSUE TITLE
Limine will fall into panic while booting on a hyper-v virtual machine 

### ISSUE THREAD

**Issue by jjwang** [Limine-Bootloader/Limine#150] opened 2022-01-26 11:44 UTC
Limine will fall into panic while booting on a hyper-v virtual machine. I attached screenshot as below:

![image](https://user-images.githubusercontent.com/1480750/151157533-a4c18c51-53db-462c-999c-51f49d35a2e9.png)

**Comment by Andy-Python-Programmer** [comment] 2022-01-27 06:24
I am not able to reproduce it. Can you provide the settings for your hyper-v machine? Also what limine version are you on?

**Comment by jjwang** [comment] 2022-01-27 14:24
I tested with limine-barebones project without too much modifications. The limine version is 2.24. I also tested the latest binary and panic also happened. The hyper-v machine is default gen-1 setting and I launched limine from cdrom. I hope it can help.

**Comment by Mintsuki** [comment] 2022-01-28 09:28
Please, try using the latest Limine release and see if you can reproduce this issue.

**Comment by jjwang** [comment] 2022-02-01 05:24
Thanks for your suggestion! I will retry with lastest release and report later.

**Comment by jjwang** [comment] 2022-02-07 11:54
I tried to build with latest limine code and stivale2-barebones, the panic changes to:

![image](https://user-images.githubusercontent.com/1480750/152783446-26aa608e-26ae-4de2-9e41-52c8e50bd736.png)

**Comment by 48cf** [comment] 2022-02-07 15:09
Can somewhat reproduce on default Hyper-V gen1 VM using stivale2-barebones with Limine v2.83, although I'm getting a different panic.

![image](https://user-images.githubusercontent.com/32851089/152814815-54f31913-7606-433e-85b0-dc6c4992fdbe.png)

**Comment by 48cf** [comment] 2022-02-07 15:26
I also noticed that if you run the VM with at least 1946MiB of memory assigned to it you instead get a different panic 🤔

![image](https://user-images.githubusercontent.com/32851089/152817802-ed502adf-1fea-44f4-bfbf-997b5f92dd73.png)

**Closed as completed** 2022-02-09 11:45 UTC
Labels: unconfirmed-bug
